{
 "title": "Namada Validator/Node Dashboard Copy",
 "description": "By \"AM Solutions\"",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Validator Missed Blocks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(namada_tm_consensus_validator_missed_blocks{chain_id=\"shielded-expedition.88f17d1d14\"}[5m])",
     "legendFormat": "5 min"
    },
    {
     "expr": "rate(namada_tm_consensus_validator_missed_blocks{chain_id=\"public-testnet-15.88f17d1d14\"}[6h])",
     "legendFormat": "6 hrs"
    }
   ]
  },
  {
   "title": "Missed Blocks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_consensus_validator_missed_blocks{chain_id=\"shielded-expedition.88f17d1d14\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voting Power Tendency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(namada_tm_consensus_validator_power{chain_id=\"shielded-expedition.88f17d1d14\"})/1000000",
     "legendFormat": "{{validator_address}}"
    }
   ]
  },
  {
   "title": "Voting Power",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(namada_tm_consensus_validator_power{chain_id=\"shielded-expedition.88f17d1d14\"})/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chain Height",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_consensus_height{chain_id=\"shielded-expedition.88f17d1d14\"}",
     "legendFormat": "{{chain_id}}"
    }
   ]
  },
  {
   "title": "Chain Height Flow",
   "type": "timeseries",
   "description": "consensus height",
   "gridPos": { "h": 5, "w": 7, "x": 3, "y": 6 },
   "targets": [
    {
     "expr": "namada_tm_consensus_height{chain_id=\"shielded-expedition.88f17d1d14\"}",
     "legendFormat": "{{chain_id}}"
    }
   ]
  },
  {
   "title": "Validators (Active)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_consensus_validators{chain_id=\"shielded-expedition.88f17d1d14\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peers Connected",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "namada_tm_p2p_peers{chain_id=\"shielded-expedition.88f17d1d14\"}",
     "legendFormat": "Peers Tendency"
    }
   ]
  },
  {
   "title": "Peers Connected",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_p2p_peers{chain_id=\"shielded-expedition.88f17d1d14\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voting Power Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(namada_tm_consensus_validators_power{chain_id=\"shielded-expedition.88f17d1d14\"})/1000000",
     "legendFormat": "Voting Power Total"
    }
   ]
  },
  {
   "title": "Total TX`s",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_consensus_total_txs{chain_id=\"shielded-expedition.88f17d1d14\"}",
     "legendFormat": "{{chain_id}}"
    }
   ]
  },
  {
   "title": "Transactons flow",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "namada_tm_consensus_num_txs{chain_id=\"shielded-expedition.88f17d1d14\"}",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "Recheked TX's",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_mempool_recheck_times{chain_id=\"shielded-expedition.88f17d1d14\"} ",
     "legendFormat": "{{chain_id}}"
    }
   ]
  },
  {
   "title": "Uncommitted transactions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_mempool_size{chain_id=\"shielded-expedition.88f17d1d14\"}",
     "legendFormat": "Uncommitted transactions"
    }
   ]
  },
  {
   "title": "Block Size (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "namada_tm_consensus_block_size_bytes{chain_id=\"shielded-expedition.88f17d1d14\"}",
     "legendFormat": "Block Size (Bytes)"
    }
   ]
  },
  {
   "title": "P2P Kilobytes sent TOTAL",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(namada_tm_p2p_peer_send_bytes_total{chain_id=\"shielded-expedition.88f17d1d14\"}[5m])) / 1000",
     "legendFormat": "Outbound traffic"
    }
   ]
  },
  {
   "title": "P2P Kilobytes received TOTAL",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(namada_tm_p2p_peer_receive_bytes_total{chain_id=\"shielded-expedition.88f17d1d14\"}[5m])) / 1000",
     "legendFormat": "Inbound  traffic"
    }
   ]
  }
 ]
}