gas_adjustment = 1.7
gas_prices = "0.00125ukuji"
enable_server = true
enable_voter = true

[server]
listen_addr = "0.0.0.0:7171"
read_timeout = "20s"
verbose_cors = true
write_timeout = "20s"

[[deviation_thresholds]]
base = "USDT"
threshold = "2"

[[currency_pairs]]
base = "AKT"
quote = "USD"
providers = ["crypto", "kraken", "osmosis"]

[[currency_pairs]]
base = "AKT"
quote = "USDT"
providers = ["gate", "huobi", "kucoin"]

[[currency_pairs]]
base = "ARB"
quote = "USD"
providers = ["bitfinex", "coinbase", "crypto", "kraken"]

[[currency_pairs]]
base = "ARB"
quote = "USDT"
providers = ["binance", "bitget", "bkex", "bybit", "gate", "hitbtc", "huobi", "kucoin", "lbank", "mexc", "okx", "phemex", "poloniex", "xt"]

[[currency_pairs]]
base = "ATOM"
quote = "USD"
providers = ["coinbase", "kraken", "osmosis"]

[[currency_pairs]]
base = "ATOM"
quote = "USDT"
providers = ["binance", "bitget", "bkex", "bybit", "crypto", "gate", "hitbtc", "huobi", "kucoin", "lbank", "mexc", "okx", "phemex", "poloniex", "xt"]

[[currency_pairs]]
base = "AVAX"
quote = "USD"
providers = ["bitfinex", "coinbase", "kraken"]

[[currency_pairs]]
base = "AVAX"
quote = "USDT"
providers = ["binance", "bitget", "bkex", "bybit", "crypto", "gate", "hitbtc", "huobi", "kucoin", "lbank", "mexc", "okx", "phemex", "poloniex", "xt"]

[[currency_pairs]]
base = "BAND"
quote = "USD"
providers = ["bitfinex", "coinbase", "kraken", "osmosis"]

[[currency_pairs]]
base = "BAND"
quote = "USDT"
providers = ["binance", "bitget", "bkex", "crypto", "gate", "hitbtc", "huobi", "kucoin", "okx", "phemex", "poloniex", "xt"]

[[currency_pairs]]
base = "BNB"
quote = "USDT"
providers = ["binance", "bitget", "bkex", "bybit", "gate", "hitbtc", "huobi", "kucoin", "lbank", "mexc", "okx", "phemex", "poloniex", "xt"]

[[currency_pairs]]
base = "BTC"
quote = "USD"
providers = ["bitfinex", "coinbase"]

[[currency_pairs]]
base = "BTC"
quote = "USDT"
providers = ["binance", "bitget", "bkex", "bybit", "crypto", "gate", "hitbtc", "huobi", "kucoin", "lbank", "mexc", "okx", "phemex", "poloniex", "xt"]

[[currency_pairs]]
base = "CRO"
quote = "USD"
providers = ["coinbase", "osmosis"]

[[currency_pairs]]
base = "CRO"
quote = "USDT"
providers = ["bitget", "bkex", "crypto", "gate", "kucoin", "lbank", "mexc", "okx", "xt"]

[[currency_pairs]]
base = "DOT"
quote = "USD"
providers = ["bitfinex", "coinbase", "crypto", "kraken", "osmosis"]

[[currency_pairs]]
base = "DOT"
quote = "USDT"
providers = ["binance", "bitget", "bkex", "bybit", "gate", "hitbtc", "huobi", "kucoin", "lbank", "mexc", "okx", "phemex", "poloniex", "xt"]

[[currency_pairs]]
base = "ETH"
quote = "USD"
providers = ["bitfinex", "coinbase", "crypto"]

[[currency_pairs]]
base = "ETH"
quote = "USDT"
providers = ["binance", "bitget", "bkex", "bybit", "gate", "hitbtc", "huobi", "kraken", "kucoin", "lbank", "mexc", "okx", "phemex", "poloniex", "xt"]

[[currency_pairs]]
base = "FET"
quote = "BTC"
providers = ["hitbtc"]

[[currency_pairs]]
base = "FET"
quote = "USD"
providers = ["bitfinex", "coinbase", "kraken", "osmosis"]

[[currency_pairs]]
base = "FET"
quote = "USDT"
providers = ["binance", "bitget", "crypto", "gate", "huobi", "kucoin", "lbank", "mexc", "phemex", "xt"]

[[currency_pairs]]
base = "FTM"
quote = "USD"
providers = ["bitfinex", "kraken"]

[[currency_pairs]]
base = "FTM"
quote = "USDT"
providers = ["binance", "bitget", "bkex", "bybit", "crypto", "gate", "hitbtc", "huobi", "kucoin", "lbank", "mexc", "okx", "phemex", "poloniex", "xt"]

[[currency_pairs]]
base = "GLMR"
quote = "USD"
providers = ["kraken"]

[[currency_pairs]]
base = "GLMR"
quote = "USDT"
providers = ["binance", "bitget", "bkex", "bybit", "crypto", "gate", "huobi", "kucoin", "lbank", "mexc", "okx", "xt"]

[[currency_pairs]]
base = "INJ"
quote = "BTC"
providers = ["poloniex"]

[[currency_pairs]]
base = "INJ"
quote = "USD"
providers = ["coinbase", "kraken", "osmosis"]

[[currency_pairs]]
base = "INJ"
quote = "USDT"
providers = ["binance", "bitget", "bybit", "crypto", "gate", "hitbtc", "huobi", "kucoin", "lbank", "mexc", "phemex"]

[[currency_pairs]]
base = "JUNO"
quote = "USD"
providers = ["kraken", "osmosis"]

[[currency_pairs]]
base = "JUNO"
quote = "USDT"
providers = ["bitget", "mexc"]

[[currency_pairs]]
base = "KAVA"
quote = "USD"
providers = ["coinbase", "kraken", "osmosis"]

[[currency_pairs]]
base = "KAVA"
quote = "USDT"
providers = ["binance", "bitget", "bkex", "crypto", "gate", "huobi", "kucoin", "lbank", "mexc", "xt"]

[[currency_pairs]]
base = "KUJI"
quote = "USDT"
providers = ["mexc"]
derivative = "tvwap"
derivative_period = "30m"

[[currency_pairs]]
base = "LUNA"
quote = "USD"
providers = ["bitfinex", "kraken"]

[[currency_pairs]]
base = "LUNA"
quote = "USDT"
providers = ["binance", "bitget", "bkex", "bybit", "gate", "hitbtc", "huobi", "kucoin", "lbank", "mexc", "okx", "phemex", "poloniex", "xt"]

[[currency_pairs]]
base = "LUNC"
quote = "USD"
providers = ["crypto", "osmosis"]

[[currency_pairs]]
base = "LUNC"
quote = "USDT"
providers = ["binance", "bitget", "bkex", "bybit", "gate", "hitbtc", "huobi", "kucoin", "lbank", "mexc", "okx", "phemex", "poloniex", "xt"]

[[currency_pairs]]
base = "MATIC"
quote = "USD"
providers = ["bitfinex", "coinbase", "crypto", "kraken"]

[[currency_pairs]]
base = "MATIC"
quote = "USDT"
providers = ["binance", "bitget", "bkex", "bybit", "gate", "hitbtc", "huobi", "kucoin", "lbank", "mexc", "okx", "phemex", "poloniex", "xt"]

[[currency_pairs]]
base = "OSMO"
quote = "USD"
providers = ["crypto", "osmosis"]

[[currency_pairs]]
base = "OSMO"
quote = "USDT"
providers = ["binance", "bitget", "bkex", "gate", "huobi", "kucoin", "lbank", "mexc", "xt"]

[[currency_pairs]]
base = "PAXG"
quote = "USD"
providers = ["kraken"]

[[currency_pairs]]
base = "PAXG"
quote = "USDT"
providers = ["binance", "bitget", "bybit", "crypto", "kucoin", "lbank", "mexc", "phemex", "xt"]

[[currency_pairs]]
base = "SCRT"
quote = "BTC"
providers = ["bkex"]

[[currency_pairs]]
base = "SCRT"
quote = "USD"
providers = ["kraken", "osmosis"]

[[currency_pairs]]
base = "SCRT"
quote = "USDT"
providers = ["binance", "bybit", "gate", "huobi", "kucoin", "lbank", "mexc"]

[[currency_pairs]]
base = "STATOM"
quote = "ATOM"
providers = ["osmosisv2"]
derivative = "tvwap"
derivative_period = "30m"

[[currency_pairs]]
base = "STOSMO"
quote = "OSMO"
providers = ["osmosisv2"]
derivative = "tvwap"
derivative_period = "30m"

[[currency_pairs]]
base = "USDC"
quote = "USD"
providers = ["kraken", "osmosis"]

[[currency_pairs]]
base = "USDC"
quote = "USDT"
providers = ["binance", "bitget", "bkex", "bybit", "gate", "huobi", "kucoin", "lbank", "mexc", "okx", "phemex", "xt"]

[[currency_pairs]]
base = "USDT"
quote = "USD"
providers = ["binanceus", "coinbase", "crypto", "gate", "kraken", "osmosis"]

[[currency_pairs]]
base = "USK"
quote = "USDC"
providers = ["fin"]
derivative = "tvwap"
derivative_period = "30m"

[[currency_pairs]]
base = "WBTC"
quote = "BTC"
providers = ["binance", "coinbase", "kucoin", "okx"]

[[currency_pairs]]
base = "WBTC"
quote = "USD"
providers = ["osmosis"]

[[currency_pairs]]
base = "WBTC"
quote = "USDT"
providers = ["bitget", "bybit", "crypto", "gate", "hitbtc", "mexc", "phemex", "poloniex", "xt"]


[account]

[keyring]

[rpc]


[telemetry]
enable_hostname = true
enable_hostname_label = true
enable_service_label = true
enabled = true
global_labels = [["chain-id", "kaiyo-1"]]
service_name = "price-feeder"
type = "prometheus"

[[provider_endpoints]]
name = "fin"
urls = [
  "https://kaiyo-1.gigalixirapp.com"
]

[[provider_endpoints]]
name = "osmosisv2"
urls = [
  "https://api.osmosis.zone",
  "https://api-osmosis.imperator.co",
]
