gas_adjustment = 1.8

gas_prices = "0.00125ukuji"
enable_server = true
enable_voter = true
provider_timeout = "800ms"

history_db = "/var/tmp/feeder.db"

[server]
listen_addr = "0.0.0.0:1771"
read_timeout = "20s"
verbose_cors = true
write_timeout = "20s"

[[deviation_thresholds]]
base = "USDT"
threshold = "2"

[[deviation_thresholds]]
base = "KUJI"
threshold = "2"

[[provider_min_overrides]]
denoms = ["RLB"]
providers = 1

[[provider_min_overrides]]
denoms = ["STARS", "SOMM"]
providers = 1

[[provider_min_overrides]]
denoms = ["STARS", "SOMM"]
providers = 1

[[provider_min_overrides]]
denoms = ["STATOM", "STOSMO", "MNTA", "WINK", "USK"]
providers = 1

[[provider_min_overrides]]
denoms = ["WSTETH", "WETH"]
providers = 1

[[provider_min_overrides]]
denoms = ["KUJI"]
providers = 2

[[provider_min_overrides]]
denoms = ["NTRN"]
providers = 1

[[provider_min_overrides]]
denoms = ["AMPKUJI"]
providers = 1

[[currency_pairs]]
base = "AKT"
quote = "USD"
providers = ["crypto", "kraken", "osmosis"]

[[currency_pairs]]
base = "AKT"
quote = "USDT"
providers = ["gate", "huobi", "kucoin"]

[[currency_pairs]]
base = "ARB"
quote = "USD"
providers = ["bitfinex", "coinbase", "crypto", "kraken"]

[[currency_pairs]]
base = "ARB"
quote = "USDT"
providers = ["binance", "bitget", "bkex", "bybit", "gate", "hitbtc", "huobi", "kucoin", "lbank", "mexc", "okx", "phemex", "poloniex", "xt"]

[[currency_pairs]]
base = "ATOM"
quote = "USD"
providers = ["coinbase", "kraken", "osmosis"]

[[currency_pairs]]
base = "ATOM"
quote = "USDT"
providers = ["binance", "bitget", "bkex", "bybit", "crypto", "gate", "hitbtc", "huobi", "kucoin", "lbank", "mexc", "okx", "phemex", "poloniex", "xt"]

[[currency_pairs]]
base = "AVAX"
quote = "USD"
providers = ["bitfinex", "coinbase", "kraken"]

[[currency_pairs]]
base = "AVAX"
quote = "USDT"
providers = ["binance", "bitget", "bkex", "bybit", "crypto", "gate", "hitbtc", "huobi", "kucoin", "lbank", "mexc", "okx", "phemex", "poloniex", "xt"]

[[currency_pairs]]
base = "BAND"
quote = "USD"
providers = ["bitfinex", "coinbase", "kraken", "osmosis"]

[[currency_pairs]]
base = "BAND"
quote = "USDT"
providers = ["binance", "bitget", "bkex", "crypto", "gate", "hitbtc", "huobi", "kucoin", "okx", "phemex", "poloniex", "xt"]

[[currency_pairs]]
base = "BNB"
quote = "USDT"
providers = ["binance", "bitget", "bkex", "bybit", "gate", "hitbtc", "huobi", "kucoin", "lbank", "mexc", "okx", "phemex", "poloniex", "xt"]

[[currency_pairs]]
base = "BTC"
quote = "USD"
providers = ["bitfinex", "coinbase"]

[[currency_pairs]]
base = "BTC"
quote = "USDT"
providers = ["binance", "bitget", "bkex", "bybit", "crypto", "gate", "hitbtc", "huobi", "kucoin", "lbank", "mexc", "okx", "phemex", "poloniex", "xt"]

[[currency_pairs]]
base = "CRO"
quote = "USD"
providers = ["coinbase", "osmosis"]

[[currency_pairs]]
base = "CRO"
quote = "USDT"
providers = ["bitget", "bkex", "crypto", "gate", "kucoin", "lbank", "mexc", "okx", "xt"]

[[currency_pairs]]
base = "DOT"
quote = "USD"
providers = ["bitfinex", "coinbase", "crypto", "kraken", "osmosis"]

[[currency_pairs]]
base = "DOT"
quote = "USDT"
providers = ["binance", "bitget", "bkex", "bybit", "gate", "hitbtc", "huobi", "kucoin", "lbank", "mexc", "okx", "phemex", "poloniex", "xt"]

[[currency_pairs]]
base = "ETH"
quote = "USD"
providers = ["bitfinex", "coinbase", "crypto"]

[[currency_pairs]]
base = "ETH"
quote = "USDT"
providers = ["binance", "bitget", "bkex", "bybit", "gate", "hitbtc", "huobi", "kraken", "kucoin", "lbank", "mexc", "okx", "phemex", "poloniex", "xt"]

[[currency_pairs]]
base = "FET"
quote = "BTC"
providers = ["hitbtc"]

[[currency_pairs]]
base = "FET"
quote = "USD"
providers = ["bitfinex", "coinbase", "kraken", "osmosis"]

[[currency_pairs]]
base = "FET"
quote = "USDT"
providers = ["binance", "bitget", "crypto", "gate", "huobi", "kucoin", "lbank", "mexc", "phemex", "xt"]

[[currency_pairs]]
base = "FTM"
quote = "USD"
providers = ["bitfinex", "kraken"]

[[currency_pairs]]
base = "FTM"
quote = "USDT"
providers = ["binance", "bitget", "bkex", "bybit", "crypto", "gate", "hitbtc", "huobi", "kucoin", "lbank", "mexc", "okx", "phemex", "poloniex", "xt"]

[[currency_pairs]]
base = "GLMR"
quote = "USD"
providers = ["kraken"]

[[currency_pairs]]
base = "GLMR"
quote = "USDT"
providers = ["binance", "bitget", "bkex", "bybit", "crypto", "gate", "huobi", "kucoin", "lbank", "mexc", "okx", "xt"]

[[currency_pairs]]
base = "INJ"
quote = "BTC"
providers = ["poloniex"]

[[currency_pairs]]
base = "INJ"
quote = "USD"
providers = ["coinbase", "kraken", "osmosis"]

[[currency_pairs]]
base = "INJ"
quote = "USDT"
providers = ["binance", "bitget", "bybit", "crypto", "gate", "hitbtc", "huobi", "kucoin", "lbank", "mexc", "phemex"]

[[currency_pairs]]
base = "JUNO"
quote = "USD"
providers = ["kraken", "osmosis"]

[[currency_pairs]]
base = "JUNO"
quote = "USDT"
providers = ["bitget", "mexc"]

[[currency_pairs]]
base = "KAVA"
quote = "USD"
providers = ["coinbase", "kraken", "osmosis"]

[[currency_pairs]]
base = "KAVA"
quote = "USDT"
providers = ["binance", "bitget", "bkex", "crypto", "gate", "huobi", "kucoin", "lbank", "mexc", "xt"]

[[currency_pairs]]
base = "KUJI"
quote = "USDT"
providers = ["mexc"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "KUJI"
quote = "USD"
providers = ["osmosis"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "KUJI"
quote = "USDC"
providers = ["fin"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "LUNA"
quote = "USD"
providers = ["bitfinex", "kraken"]

[[currency_pairs]]
base = "LUNA"
quote = "USDT"
providers = ["binance", "bitget", "bkex", "bybit", "gate", "hitbtc", "huobi", "kucoin", "lbank", "mexc", "okx", "phemex", "poloniex", "xt"]

[[currency_pairs]]
base = "LUNC"
quote = "USD"
providers = ["crypto", "osmosis"]

[[currency_pairs]]
base = "LUNC"
quote = "USDT"
providers = ["binance", "bitget", "bkex", "bybit", "gate", "hitbtc", "huobi", "kucoin", "lbank", "mexc", "okx", "phemex", "poloniex", "xt"]

[[currency_pairs]]
base = "MATIC"
quote = "USD"
providers = ["bitfinex", "coinbase", "crypto", "kraken"]

[[currency_pairs]]
base = "MATIC"
quote = "USDT"
providers = ["binance", "bitget", "bkex", "bybit", "gate", "hitbtc", "huobi", "kucoin", "lbank", "mexc", "okx", "phemex", "poloniex", "xt"]

[[currency_pairs]]
base = "OSMO"
quote = "USD"
providers = ["crypto", "osmosis"]

[[currency_pairs]]
base = "OSMO"
quote = "USDT"
providers = ["binance", "bitget", "bkex", "gate", "huobi", "kucoin", "lbank", "mexc", "xt"]

[[currency_pairs]]
base = "PAXG"
quote = "USD"
providers = ["kraken"]

[[currency_pairs]]
base = "PAXG"
quote = "USDT"
providers = ["binance", "bitget", "bybit", "crypto", "kucoin", "lbank", "mexc", "phemex", "xt"]

[[currency_pairs]]
base = "SCRT"
quote = "BTC"
providers = ["bkex"]

[[currency_pairs]]
base = "SCRT"
quote = "USD"
providers = ["kraken", "osmosis"]

[[currency_pairs]]
base = "SCRT"
quote = "USDT"
providers = ["binance", "bybit", "gate", "huobi", "kucoin", "lbank", "mexc"]

[[currency_pairs]]
base = "STATOM"
quote = "ATOM"
providers = ["osmosisv2"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "STOSMO"
quote = "OSMO"
providers = ["osmosisv2"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "USDC"
quote = "USD"
providers = ["kraken", "osmosis"]

[[currency_pairs]]
base = "USDC"
quote = "USDT"
providers = ["binance", "bitget", "bkex", "bybit", "gate", "huobi", "kucoin", "lbank", "mexc", "okx", "phemex", "xt"]

[[currency_pairs]]
base = "USDT"
quote = "USD"
providers = ["binanceus", "coinbase", "crypto", "gate", "kraken", "osmosis"]

[[currency_pairs]]
base = "USK"
quote = "USDC"
providers = ["fin"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "WBTC"
quote = "BTC"
providers = ["binance", "coinbase", "kucoin", "okx"]

[[currency_pairs]]
base = "WBTC"
quote = "USD"
providers = ["osmosis"]

[[currency_pairs]]
base = "WBTC"
quote = "USDT"
providers = ["bitget", "bybit", "crypto", "gate", "hitbtc", "mexc", "phemex", "poloniex", "xt"]

[[currency_pairs]]
base = "MNTA"
quote = "USDC"
providers = ["fin"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "WINK"
quote = "USK"
providers = ["fin"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "LINK"
quote = "USD"
providers = ["coinbase", "crypto", "kraken"]

[[currency_pairs]]
base = "LINK"
quote = "USDT"
providers = ["binance", "bitget", "gate", "huobi", "lbank", "okx", "phemex", "xt"]

[[currency_pairs]]
base = "UNI"
quote = "USD"
providers = ["coinbase", "crypto", "kraken"]

[[currency_pairs]]
base = "UNI"
quote = "USDT"
providers = ["binance", "bitget", "gate", "huobi", "lbank", "okx", "phemex", "poloniex", "xt"]

[[currency_pairs]]
base = "WSTETH"
quote = "WETH"
providers = ["uniswapv3"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "WETH"
quote = "USDC"
providers = ["uniswapv3"]

[[currency_pairs]]
base = "NTRN"
quote = "ATOM"
providers = ["astroport_neutron"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "AMPKUJI"
quote = "KUJI"
providers = ["finv2"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "STARS"
quote = "OSMO"
providers = ["osmosisv2"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "STARS"
quote = "USD"
providers = ["osmosis"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "SOMM"
quote = "OSMO"
providers = ["osmosisv2"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "SOMM"
quote = "USD"
providers = ["osmosis"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "RLB"
quote = "WETH"
providers = ["uniswapv3"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "RLB"
quote = "USDC"
providers = ["uniswapv3"]

[[currency_pairs]]
base = "RLB"
quote = "USDT"
providers = ["uniswapv3"]

[[currency_pairs]]
base = "HNT"
quote = "USDT"
providers = ["bitget", "gate", "okx", "kucoin", "bitmart", "bybit"]

[[currency_pairs]]
base = "HNT"
quote = "USD"
providers = ["coinbase", "crypto"]


[account]
fee_granter = ""
address = ""
chain_id = "kaiyo-1"
validator = ""
prefix = "kujira"

[keyring]
backend = "os"
dir = ""
pass = ""

[rpc]
grpc_endpoint = "localhost:9190"
rpc_timeout = "500ms"
tmrpc_endpoint = "http://localhost:26157"


[telemetry]
enable_hostname = true
enable_hostname_label = true
enable_service_label = true
enabled = true
global_labels = [["chain_id", "kayo-1"]]
service_name = "price-feeder"
type = "prometheus"
prometheus_retention = 120

[[provider_endpoints]]
name = "fin"
urls = [
  "https://kaiyo-1.gigalixirapp.com",
  "https://api.kujira.app"
]

[[provider_endpoints]]
name = "osmosisv2"
urls = [
  "https://osmosis-api.polkachu.com",
  "https://rest.cosmos.directory/osmosis",
  "https://api-osmosis-ia.cosmosia.notional.ventures",
  "https://osmosis.rest.stakin-nodes.com",
  "https://osmosis.api.kjnodes.com",
  "https://osmosis-api.lavenderfive.com:443",
]

[[provider_endpoints]]
name = "osmosis"
urls = [
  "https://api.osmosis.zone",
  "https://api-osmosis.imperator.co"
]

[[provider_endpoints]]
name = "finv2"
urls = [
  "http://127.0.0.1:1337",
  "https://kujira-api.polkachu.com",
]

[[provider_endpoints]]
name = "astroport_neutron"
urls = [
  "https://neutron-api.polkachu.com",
  "https://rest.cosmos.directory/neutron"
]

[contract_addresses.finv2]
KUJIUSDC = "kujira14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9sl4e867"
MNTAUSDC = "kujira1ws9w7wl68prspv3rut3plv8249rm0ea0kk335swye3sl2slld4lqdmc0lv"
WINKUSK = "kujira1qxtd87qus6uzvqs4jv9r0j9ccd4yla42s6qag7y8fp7hhv68nzas6hqxgw"
AMPKUJIKUJI = "kujira1lse59wt7a5yksdd08mennt299katjkfzdhmh8hvck8ln08jktcmsxrnh8s"

[contract_addresses.uniswapv3]
USDCWETH = "0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640"
WSTETHWETH = "0x109830a1AAaD605BbF02a9dFA7B0B92EC2FB7dAa"
RLBUSDC = "0x2322e5517a3cbc75a3f02d74c96f82dda120d841"
RLBWETH = "0x510100d5143e011db24e2aa38abe85d73d5b2177"
RLBUSDT = "0x33676385160f9d8f03a0db2821029882f7c79e93"

[contract_addresses.astroport_neutron]
NTRNATOM = "neutron1e22zh5p8meddxjclevuhjmfj69jxfsa8uu3jvht72rv9d8lkhves6t8veq"

[contract_addresses.osmosisv2]
ATOMSTATOM = "803"
STOSMOOSMO = "833"
MNTAOSMO = "1215"
SOMMOSMO = "627"
STARSOSMO = "1096"

[contract_addresses.camelotv2]
KUJIUSDC = "0xDB7D929434F0a52fFE3E5631044776b23E6f8a67"

[contract_addresses.camelotv3]
WETHUSDC = "0x521aa84ab3fcc4c05cABaC24Dc3682339887B126"


