gas_adjustment = 1.9
provider_timeout = "1000000s"

[server]
listen_addr = "0.0.0.0:7171"
read_timeout = "20s"
verbose_cors = true
write_timeout = "20s"

[[currency_pairs]]
base = "UMEE"
providers = [
  "mexc",
  "gate",
]
quote = "USDT"

[[currency_pairs]]
base = "UMEE"
providers = [
  "osmosis",
]
quote = "ATOM"

[[currency_pairs]]
base = "USDT"
providers = [
  "kraken",
  "coinbase",
  "crypto",
]
quote = "USD"

[[currency_pairs]]
base = "USDC"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "ATOM"
providers = [
  "okx",
  "bitget",
]
quote = "USDT"

[[currency_pairs]]
base = "ATOM"
providers = [
  "kraken",
  "crypto",
]
quote = "USD"

[[currency_pairs]]
base = "USDC"
providers = [
  "okx",
  "bitget",
  "kraken",
]
quote = "USDT"

[[currency_pairs]]
base = "DAI"
providers = [
  "okx",
  "bitget",
  "huobi",
]
quote = "USDT"

[[currency_pairs]]
base = "DAI"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "ETH"
providers = [
  "okx",
  "bitget",
]
quote = "USDT"

[[currency_pairs]]
base = "ETH"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "WBTC"
providers = [
  "okx",
  "bitget",
  "crypto",
]
quote = "USDT"

[[currency_pairs]]
base = "CRO"
providers = [
  "crypto",
  "bitget",
  "okx",
]
quote = "USDT"

[[currency_pairs]]
base = "BNB"
providers = [
  "mexc",
  "bitget",
  "okx",
]
quote = "USDT"

[[currency_pairs]]
base = "OSMO"
providers = [
  "osmosis",
]
quote = "ATOM"

[[currency_pairs]]
base = "OSMO"
providers = [
  "bitget",
  "gate",
]
quote = "USDT"

[[currency_pairs]]
base = "OSMO"
providers = [
  "crypto",
]
quote = "USD"

[[currency_pairs]]
base = "WETH"
providers = [
  "eth-uniswap"
]
quote = "USDC"

[[currency_pairs]]
base = "WBTC"
providers = [
  "eth-uniswap"
]
quote = "WETH"

[[currency_pairs]]
base = "CBETH"
providers = [
  "eth-uniswap"
]
quote = "WETH"

[[currency_pairs]]
base = "stATOM"
providers = [
  "osmosis",
]
quote = "ATOM"

[[currency_pairs]]
base = "stOSMO"
providers = [
  "osmosis",
]
quote = "OSMO"

[[currency_pairs]]
base = "IST"
providers = [
  "osmosis",
]
quote = "OSMO"

[[currency_pairs]]
base = "IST"
providers = [
  "crescent",
]
quote = "USDC"

[[currency_pairs]]
base = "USDC"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "AKT"
quote = "USDT"
providers = [ "huobi", "gate",]

[[currency_pairs]]
base = "AKT"
quote = "USD"
providers = [ "kraken", "crypto",]

[[currency_pairs]]
base = "JUNO"
quote = "USDT"
providers = [ "bitget", "mexc",]

[[currency_pairs]]
base = "JUNO"
quote = "USD"
providers = [ "kraken",]

[[currency_pairs]]
base = "JUNO"
quote = "ATOM"
providers = [ "osmosis",]

[[currency_pairs]]
base = "LUNA"
quote = "USDT"
providers = [ "okx", "gate", "huobi", "bitget",]

[[currency_pairs]]
base = "WAXL"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "WAXL"
providers = [
  "huobi",
  "bitget",
  "gate",
]
quote = "USDT"

[[currency_pairs]]
base = "DOT"
providers = [
  "kraken",
  "coinbase",
  "crypto",
]
quote = "USD"

[[currency_pairs]]
base = "DOT"
providers = [
  "gate",
  "bitget",
]
quote = "USDT"

[[currency_pairs]]
base = "MATIC"
providers = [
  "coinbase",
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "MATIC"
providers = [
  "gate",
  "mexc",
  "bitget",
]
quote = "USDT"

[[currency_pairs]]
base = "stkATOM"
providers = [
  "osmosis",
]
quote = "ATOM"

[[currency_pairs]]
base = "qATOM"
providers = [
  "osmosis",
]
quote = "ATOM"

[[currency_pairs]]
base = "CBETH"
quote = "USD"
providers = [ "coinbase",]

[[currency_pairs]]
base = "CMST"
providers = [
  "osmosis",
]
quote = "OSMO"

[[currency_pairs]]
base = "MARS"
providers = [
  "osmosis",
]
quote = "OSMO"

[[currency_pairs]]
base = "stJUNO"
providers = [
  "osmosis",
]
quote = "JUNO"

[[currency_pairs]]
base = "USK"
providers = [
  "kujira",
]
quote = "USDC"

[[currency_pairs]]
base = "stUMEE"
providers = [
  "osmosis",
]
quote = "UMEE"

[[currency_pairs]]
base = "RETH"
providers = [
  "eth-uniswap",
]
quote = "WETH"

[[currency_pairs]]
base = "NCT"
providers = [
  "osmosis",
]
quote = "OSMO"

[[currency_pairs]]
base = "SOMM"
providers = [
  "osmosis",
]
quote = "OSMO"

[[currency_pairs]]
base = "SOMM"
providers = [
  "gate",
]
quote = "USDT"

[[currency_pairs]]
base = "STARS"
providers = [
  "osmosis",
]
quote = "ATOM"

[[currency_pairs]]
base = "STARS"
providers = [
  "osmosis",
]
quote = "OSMO"

[[currency_pairs]]
base = "INJ"
providers = [
  "binance",
  "gate",
  "bitget",
  "mexc",
]
quote = "USDT"

[[currency_pairs]]
base = "SFRXETH"
providers = [
  "eth-uniswap"
]
quote = "WETH"

[[currency_pairs]]
base = "WSTETH"
providers = [
  "eth-uniswap"
]
quote = "WETH"

[[currency_pairs]]
base = "TIA"
providers = [
  "binance",
  "okx",
  "bitget",
  "gate",
]
quote = "USDT"
[[deviation_thresholds]]
base = "MARS"
threshold = "1.5"

[[deviation_thresholds]]
base = "CMST"
threshold = "1.5"

[[deviation_thresholds]]
base = "USDT"
threshold = "1.5"

[[deviation_thresholds]]
base = "UMEE"
threshold = "1.5"

[[deviation_thresholds]]
base = "ATOM"
threshold = "1.5"

[[deviation_thresholds]]
base = "USDC"
threshold = "1.5"

[[deviation_thresholds]]
base = "CRO"
threshold = "1.5"

[[deviation_thresholds]]
base = "DAI"
threshold = "2"

[[deviation_thresholds]]
base = "ETH"
threshold = "2"

[[deviation_thresholds]]
base = "BTC"
threshold = "2"

[[deviation_thresholds]]
base = "BNB"
threshold = "2"

[[deviation_thresholds]]
base = "JUNO"
threshold = "2"

[[deviation_thresholds]]
base = "OSMO"
threshold = "2"

[[deviation_thresholds]]
base = "stATOM"
threshold = "2"

[[deviation_thresholds]]
base = "stOSMO"
threshold = "2"

[[deviation_thresholds]]
base = "IST"
threshold = "2"

[[deviation_thresholds]]
base = "AKT"
threshold = "1.5"

[[deviation_thresholds]]
base = "LUNA"
threshold = "1.5"

[[deviation_thresholds]]
base = "WAXL"
threshold = "1.5"

[[deviation_thresholds]]
base = "MATIC"
threshold = "1.5"

[[deviation_thresholds]]
base = "DOT"
threshold = "1.5"

[[deviation_thresholds]]
base = "stkATOM"
threshold = "1.5"

[[deviation_thresholds]]
base = "qATOM"
threshold = "1.5"

[[deviation_thresholds]]
base = "CBETH"
threshold = "1.5"

[[deviation_thresholds]]
base = "stJUNO"
threshold = "2"

[[deviation_thresholds]]
base = "USK"
threshold = "2"

[[deviation_thresholds]]
base = "stUMEE"
threshold = "2"

[[deviation_thresholds]]
base = "RETH"
threshold = "2"

[[deviation_thresholds]]
base = "LINK"
threshold = "2"

[[deviation_thresholds]]
base = "WETH"
threshold = "2"

[[deviation_thresholds]]
base = "WBTC"
threshold = "2"

[[deviation_thresholds]]
base = "NCT"
threshold = "2"

[[deviation_thresholds]]
base = "SOMM"
threshold = "2"

[[deviation_thresholds]]
base = "STARS"
threshold = "2"

[[deviation_thresholds]]
base = "INJ"
threshold = "2"

[[deviation_thresholds]]
base = "SFRXETH"
threshold = "2"

[[deviation_thresholds]]
base = "WSTETH"
threshold = "2"

[[deviation_thresholds]]
base = "TIA"
threshold = "2"

[[provider_endpoints]]
name = "binance"
rest = "https://api1.binance.com"
websocket = "stream.binance.com:9443"

[account]
address = "umee1..."
chain_id = "umee-1"
validator = "umeevaloper1"

backend = "os"
dir = "/home/umee/.umee"
pass = ""

[rpc]
grpc_endpoint = "localhost:9090"
rpc_timeout = "100ms"
tmrpc_endpoint = "http://localhost:26657"

[telemetry]
enable-hostname = true
enable-hostname-label = true
enable-service-label = true
enabled = true
global-labels = [["chain_id", "umee-1"]]
service-name = "price-feeder"
prometheus-retention-time = 100
